exports.HTTP_STATUS_CODE = {
  SUCCESS: 200,
  CREATED: 201,
  UNAUTHORIZED: 401,
  INVALID_DATA: 406,
  INTERNAL_ERROR: 500,
  BAD_REQUEST: 400,
  NOT_FOUND: 404
};
exports.SUCCESS = 'Successfully data retrieved';
